(function(q,A){var w=q.GreenSockGlobals=q.GreenSockGlobals||q;if(!w.TweenLite){var t,s,c,p,u,v=function(b){var r=b.split("."),d=w;for(b=0;r.length>b;b++)d[r[b]]=d=d[r[b]]||{};return d},z=v("com.greensock"),D=function(b){var r,d=[],a=b.length;for(r=0;r!==a;d.push(b[r++]));return d},M=function(){},C=function(){var b=Object.prototype.toString,r=b.call([]);return function(d){return null!=d&&(d instanceof Array||"object"==typeof d&&!!d.push&&b.call(d)===r)}}(),B={},x=function(b,r,d,a){this.sc=B[b]?B[b].sc:
[];B[b]=this;this.gsClass=null;this.func=d;var g=[];this.check=function(h){for(var c,f,l=r.length,n=l;-1<--l;)(c=B[r[l]]||new x(r[l],[])).gsClass?(g[l]=c.gsClass,n--):h&&c.sc.push(this);if(0===n&&d)for(h=("com.greensock."+b).split("."),c=h.pop(),f=v(h.join("."))[c]=this.gsClass=d.apply(d,g),a&&(w[c]=f,"function"==typeof define&&define.amd?define((q.GreenSockAMDPath?q.GreenSockAMDPath+"/":"")+b.split(".").pop(),[],function(){return f}):b===A&&"undefined"!=typeof module&&module.exports&&(module.exports=
f)),l=0;this.sc.length>l;l++)this.sc[l].check()};this.check(!0)},a=q._gsDefine=function(b,r,d,a){return new x(b,r,d,a)},l=z._class=function(b,r,d){return r=r||function(){},a(b,[],function(){return r},d),r};a.globals=w;var m=[0,0,1,1],T=[],E=l("easing.Ease",function(b,r,d,a){this._func=b;this._type=d||0;this._power=a||0;this._params=r?m.concat(r):m},!0),O=E.map={},I=E.register=function(b,r,d,a){var g,h,c;r=r.split(",");for(var f=r.length,k=(d||"easeIn,easeOut,easeInOut").split(",");-1<--f;)for(g=r[f],
d=a?l("easing."+g,null,!0):z.easing[g]||{},h=k.length;-1<--h;)c=k[h],O[g+"."+c]=O[c+g]=d[c]=b.getRatio?b:b[c]||new b};c=E.prototype;c._calcEnd=!1;c.getRatio=function(b){if(this._func)return this._params[0]=b,this._func.apply(null,this._params);var r=this._type,d=this._power,a=1===r?1-b:2===r?b:.5>b?2*b:2*(1-b);return 1===d?a*=a:2===d?a*=a*a:3===d?a*=a*a*a:4===d&&(a*=a*a*a*a),1===r?1-a:2===r?a:.5>b?a/2:1-a/2};t=["Linear","Quad","Cubic","Quart","Quint,Strong"];for(s=t.length;-1<--s;)c=t[s]+",Power"+
s,I(new E(null,null,1,s),c,"easeOut",!0),I(new E(null,null,2,s),c,"easeIn"+(0===s?",easeNone":"")),I(new E(null,null,3,s),c,"easeInOut");O.linear=z.easing.Linear.easeIn;O.swing=z.easing.Quad.easeInOut;var Z=l("events.EventDispatcher",function(b){this._listeners={};this._eventTarget=b||this});c=Z.prototype;c.addEventListener=function(b,a,d,e,g){g=g||0;var h,c=this._listeners[b],f=0;null==c&&(this._listeners[b]=c=[]);for(h=c.length;-1<--h;)b=c[h],b.c===a&&b.s===d?c.splice(h,1):0===f&&g>b.pr&&(f=h+1);
c.splice(f,0,{c:a,s:d,up:e,pr:g});this!==p||u||p.wake()};c.removeEventListener=function(b,a){var d,e=this._listeners[b];if(e)for(d=e.length;-1<--d;)if(e[d].c===a)return e.splice(d,1),void 0};c.dispatchEvent=function(b){var a,d,e,g=this._listeners[b];if(g)for(a=g.length,d=this._eventTarget;-1<--a;)e=g[a],e.up?e.c.call(e.s||d,{type:b,target:d}):e.c.call(e.s||d)};var P=q.requestAnimationFrame,U=q.cancelAnimationFrame,Q=Date.now||function(){return(new Date).getTime()},N=Q();t=["ms","moz","webkit","o"];
for(s=t.length;-1<--s&&!P;)P=q[t[s]+"RequestAnimationFrame"],U=q[t[s]+"CancelAnimationFrame"]||q[t[s]+"CancelRequestAnimationFrame"];l("Ticker",function(b,a){var d,e,g,h,c,f=this,l=Q(),n=!1!==a&&P,k=500,m=33,q=function(b){var a,r;a=Q()-N;a>k&&(l+=a-m);N+=a;f.time=(N-l)/1E3;a=f.time-c;(!d||0<a||!0===b)&&(f.frame++,c+=a+(a>=h?.004:h-a),r=!0);!0!==b&&(g=e(q));r&&f.dispatchEvent("tick")};Z.call(f);f.time=f.frame=0;f.tick=function(){q(!0)};f.lagSmoothing=function(b,a){k=b||1E10;m=Math.min(a,k,0)};f.sleep=
function(){null!=g&&(n&&U?U(g):clearTimeout(g),e=M,g=null,f===p&&(u=!1))};f.wake=function(){null!==g?f.sleep():10<f.frame&&(N=Q()-k+5);e=0===d?M:n&&P?P:function(b){return setTimeout(b,0|1E3*(c-f.time)+1)};f===p&&(u=!0);q(2)};f.fps=function(b){return arguments.length?(d=b,h=1/(d||60),c=this.time+h,f.wake(),void 0):d};f.useRAF=function(b){return arguments.length?(f.sleep(),n=b,f.fps(d),void 0):n};f.fps(b);setTimeout(function(){n&&(!g||5>f.frame)&&f.useRAF(!1)},1500)});c=z.Ticker.prototype=new z.events.EventDispatcher;
c.constructor=z.Ticker;var y=l("core.Animation",function(b,a){if(this.vars=a=a||{},this._duration=this._totalDuration=b||0,this._delay=Number(a.delay)||0,this._timeScale=1,this._active=!0===a.immediateRender,this.data=a.data,this._reversed=!0===a.reversed,G){u||p.wake();var d=this.vars.useFrames?J:G;d.add(this,d._time);this.vars.paused&&this.paused(!0)}});p=y.ticker=new z.Ticker;c=y.prototype;c._dirty=c._gc=c._initted=c._paused=!1;c._totalTime=c._time=0;c._rawPrevTime=-1;c._next=c._last=c._onUpdate=
c._timeline=c.timeline=null;c._paused=!1;var $=function(){u&&2E3<Q()-N&&p.wake();setTimeout($,2E3)};$();c.play=function(b,a){return null!=b&&this.seek(b,a),this.reversed(!1).paused(!1)};c.pause=function(b,a){return null!=b&&this.seek(b,a),this.paused(!0)};c.resume=function(b,a){return null!=b&&this.seek(b,a),this.paused(!1)};c.seek=function(b,a){return this.totalTime(Number(b),!1!==a)};c.restart=function(b,a){return this.reversed(!1).paused(!1).totalTime(b?-this._delay:0,!1!==a,!0)};c.reverse=function(b,
a){return null!=b&&this.seek(b||this.totalDuration(),a),this.reversed(!0).paused(!1)};c.render=function(){};c.invalidate=function(){return this};c.isActive=function(){var b,a=this._timeline,d=this._startTime;return!a||!this._gc&&!this._paused&&a.isActive()&&(b=a.rawTime())>=d&&d+this.totalDuration()/this._timeScale>b};c._enabled=function(b,a){return u||p.wake(),this._gc=!b,this._active=this.isActive(),!0!==a&&(b&&!this.timeline?this._timeline.add(this,this._startTime-this._delay):!b&&this.timeline&&
this._timeline._remove(this,!0)),!1};c._kill=function(){return this._enabled(!1,!1)};c.kill=function(b,a){return this._kill(b,a),this};c._uncache=function(b){for(b=b?this:this.timeline;b;)b._dirty=!0,b=b.timeline;return this};c._swapSelfInParams=function(b){for(var a=b.length,d=b.concat();-1<--a;)"{self}"===b[a]&&(d[a]=this);return d};c.eventCallback=function(b,a,d,e){if("on"===(b||"").substr(0,2)){var g=this.vars;if(1===arguments.length)return g[b];null==a?delete g[b]:(g[b]=a,g[b+"Params"]=C(d)&&
-1!==d.join("").indexOf("{self}")?this._swapSelfInParams(d):d,g[b+"Scope"]=e);"onUpdate"===b&&(this._onUpdate=a)}return this};c.delay=function(b){return arguments.length?(this._timeline.smoothChildTiming&&this.startTime(this._startTime+b-this._delay),this._delay=b,this):this._delay};c.duration=function(b){return arguments.length?(this._duration=this._totalDuration=b,this._uncache(!0),this._timeline.smoothChildTiming&&0<this._time&&this._time<this._duration&&0!==b&&this.totalTime(b/this._duration*
this._totalTime,!0),this):(this._dirty=!1,this._duration)};c.totalDuration=function(b){return this._dirty=!1,arguments.length?this.duration(b):this._totalDuration};c.time=function(b,a){return arguments.length?(this._dirty&&this.totalDuration(),this.totalTime(b>this._duration?this._duration:b,a)):this._time};c.totalTime=function(b,a,d){if(u||p.wake(),!arguments.length)return this._totalTime;if(this._timeline){if(0>b&&!d&&(b+=this.totalDuration()),this._timeline.smoothChildTiming){this._dirty&&this.totalDuration();
var e=this._totalDuration,g=this._timeline;if(b>e&&!d&&(b=e),this._startTime=(this._paused?this._pauseTime:g._time)-(this._reversed?e-b:b)/this._timeScale,g._dirty||this._uncache(!1),g._timeline)for(;g._timeline;)g._timeline._time!==(g._startTime+g._totalTime)/g._timeScale&&g.totalTime(g._totalTime,!0),g=g._timeline}this._gc&&this._enabled(!0,!1);(this._totalTime!==b||0===this._duration)&&(this.render(b,a,!1),H.length&&R())}return this};c.progress=c.totalProgress=function(b,a){return arguments.length?
this.totalTime(this.duration()*b,a):this._time/this.duration()};c.startTime=function(b){return arguments.length?(b!==this._startTime&&(this._startTime=b,this.timeline&&this.timeline._sortChildren&&this.timeline.add(this,b-this._delay)),this):this._startTime};c.timeScale=function(b){if(!arguments.length)return this._timeScale;if(b=b||1E-10,this._timeline&&this._timeline.smoothChildTiming){var a=this._pauseTime,a=a||0===a?a:this._timeline.totalTime();this._startTime=a-(a-this._startTime)*this._timeScale/
b}return this._timeScale=b,this._uncache(!1)};c.reversed=function(b){return arguments.length?(b!=this._reversed&&(this._reversed=b,this.totalTime(this._timeline&&!this._timeline.smoothChildTiming?this.totalDuration()-this._totalTime:this._totalTime,!0)),this):this._reversed};c.paused=function(b){if(!arguments.length)return this._paused;if(b!=this._paused&&this._timeline){u||b||p.wake();var a=this._timeline,d=a.rawTime(),e=d-this._pauseTime;!b&&a.smoothChildTiming&&(this._startTime+=e,this._uncache(!1));
this._pauseTime=b?d:null;this._paused=b;this._active=this.isActive();!b&&0!==e&&this._initted&&this.duration()&&this.render(a.smoothChildTiming?this._totalTime:(d-this._startTime)/this._timeScale,!0,!0)}return this._gc&&!b&&this._enabled(!0,!1),this};s=l("core.SimpleTimeline",function(b){y.call(this,0,b);this.autoRemoveChildren=this.smoothChildTiming=!0});c=s.prototype=new y;c.constructor=s;c.kill()._gc=!1;c._first=c._last=null;c._sortChildren=!1;c.add=c.insert=function(b,a){var d,e;if(b._startTime=
Number(a||0)+b._delay,b._paused&&this!==b._timeline&&(b._pauseTime=b._startTime+(this.rawTime()-b._startTime)/b._timeScale),b.timeline&&b.timeline._remove(b,!0),b.timeline=b._timeline=this,b._gc&&b._enabled(!0,!0),d=this._last,this._sortChildren)for(e=b._startTime;d&&d._startTime>e;)d=d._prev;return d?(b._next=d._next,d._next=b):(b._next=this._first,this._first=b),b._next?b._next._prev=b:this._last=b,b._prev=d,this._timeline&&this._uncache(!0),this};c._remove=function(b,a){return b.timeline===this&&
(a||b._enabled(!1,!0),b._prev?b._prev._next=b._next:this._first===b&&(this._first=b._next),b._next?b._next._prev=b._prev:this._last===b&&(this._last=b._prev),b._next=b._prev=b.timeline=null,this._timeline&&this._uncache(!0)),this};c.render=function(b,a,d){var e,g=this._first;for(this._totalTime=this._time=this._rawPrevTime=b;g;)e=g._next,(g._active||b>=g._startTime&&!g._paused)&&(g._reversed?g.render((g._dirty?g.totalDuration():g._totalDuration)-(b-g._startTime)*g._timeScale,a,d):g.render((b-g._startTime)*
g._timeScale,a,d)),g=e};c.rawTime=function(){return u||p.wake(),this._totalTime};var k=l("TweenLite",function(b,a,d){if(y.call(this,a,d),this.render=k.prototype.render,null==b)throw"Cannot tween a null target.";this.target=b="string"!=typeof b?b:k.selector(b)||b;var e,g;e=b.jquery||b.length&&b!==q&&b[0]&&(b[0]===q||b[0].nodeType&&b[0].style&&!b.nodeType);d=this.vars.overwrite;if(this._overwrite=d=null==d?aa[k.defaultOverwrite]:"number"==typeof d?d>>0:aa[d],(e||b instanceof Array||b.push&&C(b))&&"number"!=
typeof b[0])for(this._targets=g=D(b),this._propLookup=[],this._siblings=[],b=0;g.length>b;b++)(e=g[b])?"string"!=typeof e?e.length&&e!==q&&e[0]&&(e[0]===q||e[0].nodeType&&e[0].style&&!e.nodeType)?(g.splice(b--,1),this._targets=g=g.concat(D(e))):(this._siblings[b]=S(e,this,!1),1===d&&1<this._siblings[b].length&&V(e,this,null,1,this._siblings[b])):(e=g[b--]=k.selector(e),"string"==typeof e&&g.splice(b+1,1)):g.splice(b--,1);else this._propLookup={},this._siblings=S(b,this,!1),1===d&&1<this._siblings.length&&
V(b,this,null,1,this._siblings);(this.vars.immediateRender||0===a&&0===this._delay&&!1!==this.vars.immediateRender)&&(this._time=-1E-10,this.render(-this._delay))},!0),W=function(b){return b.length&&b!==q&&b[0]&&(b[0]===q||b[0].nodeType&&b[0].style&&!b.nodeType)};c=k.prototype=new y;c.constructor=k;c.kill()._gc=!1;c.ratio=0;c._firstPT=c._targets=c._overwrittenProps=c._startAt=null;c._notifyPluginsOfEnabled=c._lazy=!1;k.version="1.13.1";k.defaultEase=c._ease=new E(null,null,1,1);k.defaultOverwrite=
"auto";k.ticker=p;k.autoSleep=!0;k.lagSmoothing=function(b,a){p.lagSmoothing(b,a)};k.selector=q.$||q.jQuery||function(b){var a=q.$||q.jQuery;return a?(k.selector=a,a(b)):"undefined"==typeof document?b:document.querySelectorAll?document.querySelectorAll(b):document.getElementById("#"===b.charAt(0)?b.substr(1):b)};var H=[],X={},I=k._internals={isArray:C,isSelector:W,lazyTweens:H},K=k._plugins={},L=I.tweenLookup={},ca=0,Y=I.reservedProps={ease:1,delay:1,overwrite:1,onComplete:1,onCompleteParams:1,onCompleteScope:1,
useFrames:1,runBackwards:1,startAt:1,onUpdate:1,onUpdateParams:1,onUpdateScope:1,onStart:1,onStartParams:1,onStartScope:1,onReverseComplete:1,onReverseCompleteParams:1,onReverseCompleteScope:1,onRepeat:1,onRepeatParams:1,onRepeatScope:1,easeParams:1,yoyo:1,immediateRender:1,repeat:1,repeatDelay:1,data:1,paused:1,reversed:1,autoCSS:1,lazy:1},aa={none:0,all:1,auto:2,concurrent:3,allOnStart:4,preexisting:5,"true":1,"false":0},J=y._rootFramesTimeline=new s,G=y._rootTimeline=new s,R=I.lazyRender=function(){var b=
H.length;for(X={};-1<--b;)(t=H[b])&&!1!==t._lazy&&(t.render(t._lazy,!1,!0),t._lazy=!1);H.length=0};G._startTime=p.time;J._startTime=p.frame;G._active=J._active=!0;setTimeout(R,1);y._updateRoot=k.render=function(){var b,a,d;if(H.length&&R(),G.render((p.time-G._startTime)*G._timeScale,!1,!1),J.render((p.frame-J._startTime)*J._timeScale,!1,!1),H.length&&R(),!(p.frame%120)){for(d in L){a=L[d].tweens;for(b=a.length;-1<--b;)a[b]._gc&&a.splice(b,1);0===a.length&&delete L[d]}if(d=G._first,(!d||d._paused)&&
k.autoSleep&&!J._first&&1===p._listeners.tick.length){for(;d&&d._paused;)d=d._next;d||p.sleep()}}};p.addEventListener("tick",y._updateRoot);var S=function(b,a,d){var e,g,c=b._gsTweenID;if(L[c||(b._gsTweenID=c="t"+ca++)]||(L[c]={target:b,tweens:[]}),a&&(e=L[c].tweens,e[g=e.length]=a,d))for(;-1<--g;)e[g]===a&&e.splice(g,1);return L[c].tweens},V=function(b,a,d,e,g){var c,l,f;if(1===e||4<=e){b=g.length;for(c=0;b>c;c++)if((f=g[c])!==a)f._gc||f._enabled(!1,!1)&&(l=!0);else if(5===e)break;return l}var k,
n=a._startTime+1E-10,m=[],q=0,p=0===a._duration;for(c=g.length;-1<--c;)(f=g[c])===a||f._gc||f._paused||(f._timeline!==a._timeline?(k=k||ba(a,0,p),0===ba(f,k,p)&&(m[q++]=f)):n>=f._startTime&&f._startTime+f.totalDuration()/f._timeScale>n&&((p||!f._initted)&&2E-10>=n-f._startTime||(m[q++]=f)));for(c=q;-1<--c;)f=m[c],2===e&&f._kill(d,b)&&(l=!0),(2!==e||!f._firstPT&&f._initted)&&f._enabled(!1,!1)&&(l=!0);return l},ba=function(b,a,d){for(var e=b._timeline,c=e._timeScale,h=b._startTime;e._timeline;){if(h+=
e._startTime,c*=e._timeScale,e._paused)return-100;e=e._timeline}return h/=c,h>a?h-a:d&&h===a||!b._initted&&2E-10>h-a?1E-10:(h+=b.totalDuration()/b._timeScale/c)>a+1E-10?0:h-a-1E-10};c._init=function(){var b,a,d,e=this.vars,c=this._overwrittenProps,h=this._duration,l=!!e.immediateRender,f=e.ease;if(e.startAt){this._startAt&&(this._startAt.render(-1,!0),this._startAt.kill());d={};for(b in e.startAt)d[b]=e.startAt[b];if(d.overwrite=!1,d.immediateRender=!0,d.lazy=l&&!1!==e.lazy,d.startAt=d.delay=null,
this._startAt=k.to(this.target,0,d),l)if(0<this._time)this._startAt=null;else if(0!==h)return}else if(e.runBackwards&&0!==h)if(this._startAt)this._startAt.render(-1,!0),this._startAt.kill(),this._startAt=null;else{d={};for(b in e)Y[b]&&"autoCSS"!==b||(d[b]=e[b]);if(d.overwrite=0,d.data="isFromStart",d.lazy=l&&!1!==e.lazy,d.immediateRender=l,this._startAt=k.to(this.target,0,d),l){if(0===this._time)return}else this._startAt._init(),this._startAt._enabled(!1)}if(this._ease=f=f?f instanceof E?f:"function"==
typeof f?new E(f,e.easeParams):O[f]||k.defaultEase:k.defaultEase,e.easeParams instanceof Array&&f.config&&(this._ease=f.config.apply(f,e.easeParams)),this._easeType=this._ease._type,this._easePower=this._ease._power,this._firstPT=null,this._targets)for(b=this._targets.length;-1<--b;)this._initProps(this._targets[b],this._propLookup[b]={},this._siblings[b],c?c[b]:null)&&(a=!0);else a=this._initProps(this.target,this._propLookup,this._siblings,c);if(a&&k._onPluginEvent("_onInitAllProps",this),c&&(this._firstPT||
"function"!=typeof this.target&&this._enabled(!1,!1)),e.runBackwards)for(d=this._firstPT;d;)d.s+=d.c,d.c=-d.c,d=d._next;this._onUpdate=e.onUpdate;this._initted=!0};c._initProps=function(b,a,d,e){var c,h,l,f,k;if(null==b)return!1;X[b._gsTweenID]&&R();if(!this.vars.css&&b.style&&b!==q&&b.nodeType&&K.css&&!1!==this.vars.autoCSS){h=this.vars;var n,m={};for(n in h)Y[n]||n in b&&"transform"!==n&&"x"!==n&&"y"!==n&&"width"!==n&&"height"!==n&&"className"!==n&&"border"!==n||!(!K[n]||K[n]&&K[n]._autoCSS)||(m[n]=
h[n],delete h[n]);h.css=m}for(c in this.vars){if(h=this.vars[c],Y[c])h&&(h instanceof Array||h.push&&C(h))&&-1!==h.join("").indexOf("{self}")&&(this.vars[c]=this._swapSelfInParams(h,this));else if(K[c]&&(f=new K[c])._onInitTween(b,this.vars[c],this)){this._firstPT=k={_next:this._firstPT,t:f,p:"setRatio",s:0,c:1,f:!0,n:c,pg:!0,pr:f._priority};for(h=f._overwriteProps.length;-1<--h;)a[f._overwriteProps[h]]=this._firstPT;(f._priority||f._onInitAllProps)&&(l=!0);(f._onDisable||f._onEnable)&&(this._notifyPluginsOfEnabled=
!0)}else this._firstPT=a[c]=k={_next:this._firstPT,t:b,p:c,f:"function"==typeof b[c],n:c,pg:!1,pr:0},k.s=k.f?b[c.indexOf("set")||"function"!=typeof b["get"+c.substr(3)]?c:"get"+c.substr(3)]():parseFloat(b[c]),k.c="string"==typeof h&&"="===h.charAt(1)?parseInt(h.charAt(0)+"1",10)*Number(h.substr(2)):Number(h)-k.s||0;k&&k._next&&(k._next._prev=k)}return e&&this._kill(e,b)?this._initProps(b,a,d,e):1<this._overwrite&&this._firstPT&&1<d.length&&V(b,this,a,this._overwrite,d)?(this._kill(a,b),this._initProps(b,
a,d,e)):(this._firstPT&&(!1!==this.vars.lazy&&this._duration||this.vars.lazy&&!this._duration)&&(X[b._gsTweenID]=!0),l)};c.render=function(b,a,d){var c,g,h,l,f=this._time,k=this._duration;h=this._rawPrevTime;if(b>=k)this._totalTime=this._time=k,this.ratio=this._ease._calcEnd?this._ease.getRatio(1):1,this._reversed||(c=!0,g="onComplete"),0===k&&(this._initted||!this.vars.lazy||d)&&(this._startTime===this._timeline._duration&&(b=0),(0===b||0>h||1E-10===h)&&h!==b&&(d=!0,1E-10<h&&(g="onReverseComplete")),
this._rawPrevTime=l=!a||b||h===b?b:1E-10);else if(1E-7>b)this._totalTime=this._time=0,this.ratio=this._ease._calcEnd?this._ease.getRatio(0):0,(0!==f||0===k&&0<h&&1E-10!==h)&&(g="onReverseComplete",c=this._reversed),0>b?(this._active=!1,0===k&&(this._initted||!this.vars.lazy||d)&&(0<=h&&(d=!0),this._rawPrevTime=l=!a||b||h===b?b:1E-10)):this._initted||(d=!0);else if(this._totalTime=this._time=b,this._easeType){var n=b/k,m=this._easeType,q=this._easePower;(1===m||3===m&&.5<=n)&&(n=1-n);3===m&&(n*=2);
1===q?n*=n:2===q?n*=n*n:3===q?n*=n*n*n:4===q&&(n*=n*n*n*n);this.ratio=1===m?1-n:2===m?n:.5>b/k?n/2:1-n/2}else this.ratio=this._ease.getRatio(b/k);if(this._time!==f||d){if(!this._initted){if(this._init(),!this._initted||this._gc)return;if(!d&&this._firstPT&&(!1!==this.vars.lazy&&this._duration||this.vars.lazy&&!this._duration))return this._time=this._totalTime=f,this._rawPrevTime=h,H.push(this),this._lazy=b,void 0;this._time&&!c?this.ratio=this._ease.getRatio(this._time/k):c&&this._ease._calcEnd&&
(this.ratio=this._ease.getRatio(0===this._time?0:1))}!1!==this._lazy&&(this._lazy=!1);this._active||!this._paused&&this._time!==f&&0<=b&&(this._active=!0);0!==f||(this._startAt&&(0<=b?this._startAt.render(b,a,d):g||(g="_dummyGS")),!this.vars.onStart||0===this._time&&0!==k||!a&&this.vars.onStart.apply(this.vars.onStartScope||this,this.vars.onStartParams||T));for(h=this._firstPT;h;)h.f?h.t[h.p](h.c*this.ratio+h.s):h.t[h.p]=h.c*this.ratio+h.s,h=h._next;this._onUpdate&&(0>b&&this._startAt&&this._startTime&&
this._startAt.render(b,a,d),a||(this._time!==f||c)&&this._onUpdate.apply(this.vars.onUpdateScope||this,this.vars.onUpdateParams||T));g&&(!this._gc||d)&&(0>b&&this._startAt&&!this._onUpdate&&this._startTime&&this._startAt.render(b,a,d),c&&(this._timeline.autoRemoveChildren&&this._enabled(!1,!1),this._active=!1),!a&&this.vars[g]&&this.vars[g].apply(this.vars[g+"Scope"]||this,this.vars[g+"Params"]||T),0===k&&1E-10===this._rawPrevTime&&1E-10!==l&&(this._rawPrevTime=0))}};c._kill=function(b,a){if("all"===
b&&(b=null),null==b&&(null==a||a===this.target))return this._lazy=!1,this._enabled(!1,!1);a="string"!=typeof a?a||this._targets||this.target:k.selector(a)||a;var d,c,g,h,l,f,m;if((C(a)||W(a))&&"number"!=typeof a[0])for(d=a.length;-1<--d;)this._kill(b,a[d])&&(f=!0);else{if(this._targets)for(d=this._targets.length;-1<--d;){if(a===this._targets[d]){l=this._propLookup[d]||{};this._overwrittenProps=this._overwrittenProps||[];c=this._overwrittenProps[d]=b?this._overwrittenProps[d]||{}:"all";break}}else{if(a!==
this.target)return!1;l=this._propLookup;c=this._overwrittenProps=b?this._overwrittenProps||{}:"all"}if(l){d=b||l;m=b!==c&&"all"!==c&&b!==l&&("object"!=typeof b||!b._tempKill);for(g in d)(h=l[g])&&(h.pg&&h.t._kill(d)&&(f=!0),h.pg&&0!==h.t._overwriteProps.length||(h._prev?h._prev._next=h._next:h===this._firstPT&&(this._firstPT=h._next),h._next&&(h._next._prev=h._prev),h._next=h._prev=null),delete l[g]),m&&(c[g]=1);!this._firstPT&&this._initted&&this._enabled(!1,!1)}}return f};c.invalidate=function(){return this._notifyPluginsOfEnabled&&
k._onPluginEvent("_onDisable",this),this._firstPT=null,this._overwrittenProps=null,this._onUpdate=null,this._startAt=null,this._initted=this._active=this._notifyPluginsOfEnabled=this._lazy=!1,this._propLookup=this._targets?{}:[],this};c._enabled=function(b,a){if(u||p.wake(),b&&this._gc){var d,c=this._targets;if(c)for(d=c.length;-1<--d;)this._siblings[d]=S(c[d],this,!0);else this._siblings=S(this.target,this,!0)}return y.prototype._enabled.call(this,b,a),this._notifyPluginsOfEnabled&&this._firstPT?
k._onPluginEvent(b?"_onEnable":"_onDisable",this):!1};k.to=function(b,a,d){return new k(b,a,d)};k.from=function(b,a,d){return d.runBackwards=!0,d.immediateRender=0!=d.immediateRender,new k(b,a,d)};k.fromTo=function(b,a,d,c){return c.startAt=d,c.immediateRender=0!=c.immediateRender&&0!=d.immediateRender,new k(b,a,c)};k.delayedCall=function(b,a,d,c,g){return new k(a,0,{delay:b,onComplete:a,onCompleteParams:d,onCompleteScope:c,onReverseComplete:a,onReverseCompleteParams:d,onReverseCompleteScope:c,immediateRender:!1,
useFrames:g,overwrite:0})};k.set=function(b,a){return new k(b,0,a)};k.getTweensOf=function(b,a){if(null==b)return[];b="string"!=typeof b?b:k.selector(b)||b;var d,c,g,l;if((C(b)||W(b))&&"number"!=typeof b[0]){d=b.length;for(c=[];-1<--d;)c=c.concat(k.getTweensOf(b[d],a));for(d=c.length;-1<--d;)for(l=c[d],g=d;-1<--g;)l===c[g]&&c.splice(d,1)}else for(c=S(b).concat(),d=c.length;-1<--d;)(c[d]._gc||a&&!c[d].isActive())&&c.splice(d,1);return c};k.killTweensOf=k.killDelayedCallsTo=function(b,a,d){"object"==
typeof a&&(d=a,a=!1);a=k.getTweensOf(b,a);for(var c=a.length;-1<--c;)a[c]._kill(d,b)};var F=l("plugins.TweenPlugin",function(a,c){this._overwriteProps=(a||"").split(",");this._propName=this._overwriteProps[0];this._priority=c||0;this._super=F.prototype},!0);if(c=F.prototype,F.version="1.10.1",F.API=2,c._firstPT=null,c._addTween=function(a,c,d,e,l,h){var k,f;return null!=e&&(k="number"==typeof e||"="!==e.charAt(1)?Number(e)-d:parseInt(e.charAt(0)+"1",10)*Number(e.substr(2)))?(this._firstPT=f={_next:this._firstPT,
t:a,p:c,s:d,c:k,f:"function"==typeof a[c],n:l||c,r:h},f._next&&(f._next._prev=f),f):void 0},c.setRatio=function(a){for(var c,d=this._firstPT;d;)c=d.c*a+d.s,d.r?c=Math.round(c):1E-6>c&&-1E-6<c&&(c=0),d.f?d.t[d.p](c):d.t[d.p]=c,d=d._next},c._kill=function(a){var c,d=this._overwriteProps,e=this._firstPT;if(null!=a[this._propName])this._overwriteProps=[];else for(c=d.length;-1<--c;)null!=a[d[c]]&&d.splice(c,1);for(;e;)null!=a[e.n]&&(e._next&&(e._next._prev=e._prev),e._prev?(e._prev._next=e._next,e._prev=
null):this._firstPT===e&&(this._firstPT=e._next)),e=e._next;return!1},c._roundProps=function(a,c){for(var d=this._firstPT;d;)(a[this._propName]||null!=d.n&&a[d.n.split(this._propName+"_").join("")])&&(d.r=c),d=d._next},k._onPluginEvent=function(a,c){var d,e,l,h,k,f=c._firstPT;if("_onInitAllProps"===a){for(;f;){k=f._next;for(e=l;e&&e.pr>f.pr;)e=e._next;(f._prev=e?e._prev:h)?f._prev._next=f:l=f;(f._next=e)?e._prev=f:h=f;f=k}f=c._firstPT=l}for(;f;)f.pg&&"function"==typeof f.t[a]&&f.t[a]()&&(d=!0),f=
f._next;return d},F.activate=function(a){for(var c=a.length;-1<--c;)a[c].API===F.API&&(K[(new a[c])._propName]=a[c]);return!0},a.plugin=function(a){if(!(a&&a.propName&&a.init&&a.API))throw"illegal plugin definition.";var c,d=a.propName,e=a.priority||0,g=a.overwriteProps,h={init:"_onInitTween",set:"setRatio",kill:"_kill",round:"_roundProps",initAll:"_onInitAllProps"},k=l("plugins."+d.charAt(0).toUpperCase()+d.substr(1)+"Plugin",function(){F.call(this,d,e);this._overwriteProps=g||[]},!0===a.global),
f=k.prototype=new F(d);f.constructor=k;k.API=a.API;for(c in h)"function"==typeof a[c]&&(f[h[c]]=a[c]);return k.version=a.version,F.activate([k]),k},t=q._gsQueue){for(s=0;t.length>s;s++)t[s]();for(c in B)B[c].func||q.console.log("GSAP encountered missing dependency: com.greensock."+c)}u=!1}})("undefined"!=typeof module&&module.exports&&"undefined"!=typeof global?global:this||window,"TweenLite");var _gsScope="undefined"!=typeof module&&module.exports&&"undefined"!=typeof global?global:this||window;
(_gsScope._gsQueue||(_gsScope._gsQueue=[])).push(function(){_gsScope._gsDefine("easing.Back",["easing.Ease"],function(q){var A,w,t,s=_gsScope.GreenSockGlobals||_gsScope,c=2*Math.PI,p=Math.PI/2,u=s.com.greensock._class,v=function(a,c){var m=u("easing."+a,function(){},!0),p=m.prototype=new q;return p.constructor=m,p.getRatio=c,m},z=q.register||function(){},D=function(a,c,m,q){c=u("easing."+a,{easeOut:new c,easeIn:new m,easeInOut:new q},!0);return z(c,a),c},M=function(a,c,m){this.t=a;this.v=c;m&&(this.next=
m,m.prev=this,this.c=m.v-c,this.gap=m.t-a)},C=function(a,c){var m=u("easing."+a,function(a){this._p1=a||0===a?a:1.70158;this._p2=1.525*this._p1},!0),p=m.prototype=new q;return p.constructor=m,p.getRatio=c,p.config=function(a){return new m(a)},m},C=D("Back",C("BackOut",function(a){return(a-=1)*a*((this._p1+1)*a+this._p1)+1}),C("BackIn",function(a){return a*a*((this._p1+1)*a-this._p1)}),C("BackInOut",function(a){return 1>(a*=2)?.5*a*a*((this._p2+1)*a-this._p2):.5*((a-=2)*a*((this._p2+1)*a+this._p2)+
2)})),B=u("easing.SlowMo",function(a,c,m){null==a?a=.7:1<a&&(a=1);this._p=1!==a?c||0===c?c:.7:0;this._p1=(1-a)/2;this._p2=a;this._p3=this._p1+this._p2;this._calcEnd=!0===m},!0),x=B.prototype=new q;return x.constructor=B,x.getRatio=function(a){var c=a+(.5-a)*this._p;return this._p1>a?this._calcEnd?1-(a=1-a/this._p1)*a:c-(a=1-a/this._p1)*a*a*a*c:a>this._p3?this._calcEnd?1-(a=(a-this._p3)/this._p1)*a:c+(a-c)*(a=(a-this._p3)/this._p1)*a*a*a:this._calcEnd?1:c},B.ease=new B(.7,.7),x.config=B.config=function(a,
c,m){return new B(a,c,m)},A=u("easing.SteppedEase",function(a){a=a||1;this._p1=1/a;this._p2=a+1},!0),x=A.prototype=new q,x.constructor=A,x.getRatio=function(a){return 0>a?a=0:1<=a&&(a=.999999999),(this._p2*a>>0)*this._p1},x.config=A.config=function(a){return new A(a)},w=u("easing.RoughEase",function(a){a=a||{};for(var c,m,p,s,t=a.taper||"none",u=[],w=0,v=s=0|(a.points||20),x=!1!==a.randomize,A=!0===a.clamp,z=a.template instanceof q?a.template:null,y="number"==typeof a.strength?.4*a.strength:.4;-1<
--v;)a=x?Math.random():1/s*v,c=z?z.getRatio(a):a,"none"===t?m=y:"out"===t?(p=1-a,m=p*p*y):"in"===t?m=a*a*y:.5>a?(p=2*a,m=.5*p*p*y):(p=2*(1-a),m=.5*p*p*y),x?c+=Math.random()*m-.5*m:v%2?c+=.5*m:c-=.5*m,A&&(1<c?c=1:0>c&&(c=0)),u[w++]={x:a,y:c};u.sort(function(a,c){return a.x-c.x});m=new M(1,1,null);for(v=s;-1<--v;)s=u[v],m=new M(s.x,s.y,m);this._prev=new M(0,0,0!==m.t?m:m.next)},!0),x=w.prototype=new q,x.constructor=w,x.getRatio=function(a){var c=this._prev;if(a>c.t){for(;c.next&&a>=c.t;)c=c.next;c=
c.prev}else for(;c.prev&&c.t>=a;)c=c.prev;return this._prev=c,c.v+(a-c.t)/c.gap*c.c},x.config=function(a){return new w(a)},w.ease=new w,D("Bounce",v("BounceOut",function(a){return 1/2.75>a?7.5625*a*a:2/2.75>a?7.5625*(a-=1.5/2.75)*a+.75:2.5/2.75>a?7.5625*(a-=2.25/2.75)*a+.9375:7.5625*(a-=2.625/2.75)*a+.984375}),v("BounceIn",function(a){return 1/2.75>(a=1-a)?1-7.5625*a*a:2/2.75>a?1-(7.5625*(a-=1.5/2.75)*a+.75):2.5/2.75>a?1-(7.5625*(a-=2.25/2.75)*a+.9375):1-(7.5625*(a-=2.625/2.75)*a+.984375)}),v("BounceInOut",
function(a){var c=.5>a;return a=c?1-2*a:2*a-1,a=1/2.75>a?7.5625*a*a:2/2.75>a?7.5625*(a-=1.5/2.75)*a+.75:2.5/2.75>a?7.5625*(a-=2.25/2.75)*a+.9375:7.5625*(a-=2.625/2.75)*a+.984375,c?.5*(1-a):.5*a+.5})),D("Circ",v("CircOut",function(a){return Math.sqrt(1-(a-=1)*a)}),v("CircIn",function(a){return-(Math.sqrt(1-a*a)-1)}),v("CircInOut",function(a){return 1>(a*=2)?-.5*(Math.sqrt(1-a*a)-1):.5*(Math.sqrt(1-(a-=2)*a)+1)})),t=function(a,l,m){var p=u("easing."+a,function(a,l){this._p1=a||1;this._p2=l||m;this._p3=
this._p2/c*(Math.asin(1/this._p1)||0)},!0);a=p.prototype=new q;return a.constructor=p,a.getRatio=l,a.config=function(a,c){return new p(a,c)},p},D("Elastic",t("ElasticOut",function(a){return this._p1*Math.pow(2,-10*a)*Math.sin((a-this._p3)*c/this._p2)+1},.3),t("ElasticIn",function(a){return-(this._p1*Math.pow(2,10*(a-=1))*Math.sin((a-this._p3)*c/this._p2))},.3),t("ElasticInOut",function(a){return 1>(a*=2)?-.5*this._p1*Math.pow(2,10*(a-=1))*Math.sin((a-this._p3)*c/this._p2):.5*this._p1*Math.pow(2,-10*
(a-=1))*Math.sin((a-this._p3)*c/this._p2)+1},.45)),D("Expo",v("ExpoOut",function(a){return 1-Math.pow(2,-10*a)}),v("ExpoIn",function(a){return Math.pow(2,10*(a-1))-.001}),v("ExpoInOut",function(a){return 1>(a*=2)?.5*Math.pow(2,10*(a-1)):.5*(2-Math.pow(2,-10*(a-1)))})),D("Sine",v("SineOut",function(a){return Math.sin(a*p)}),v("SineIn",function(a){return-Math.cos(a*p)+1}),v("SineInOut",function(a){return-.5*(Math.cos(Math.PI*a)-1)})),u("easing.EaseLookup",{find:function(a){return q.map[a]}},!0),z(s.SlowMo,
"SlowMo","ease,"),z(w,"RoughEase","ease,"),z(A,"SteppedEase","ease,"),C},!0)});_gsScope._gsDefine&&_gsScope._gsQueue.pop()();
(function(){for(var q=0,A=["ms","moz","webkit","o"],w=0;w<A.length&&!window.requestAnimationFrame;++w)window.requestAnimationFrame=window[A[w]+"RequestAnimationFrame"],window.cancelAnimationFrame=window[A[w]+"CancelAnimationFrame"]||window[A[w]+"CancelRequestAnimationFrame"];window.requestAnimationFrame||(window.requestAnimationFrame=function(t,s){var c=(new Date).getTime(),p=Math.max(0,16-(c-q)),u=window.setTimeout(function(){t(c+p)},p);q=c+p;return u});window.cancelAnimationFrame||(window.cancelAnimationFrame=
function(q){clearTimeout(q)})})();